name: Build Addon

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debugging - List files
        run: ls -la

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y zip

      - name: Create Release ZIP
        run: zip -r GlobalPlayed-${{ github.ref_name }}.zip .

      # - name: Upload to CurseForge
      #   uses: BigWigsMods/packager@master
      #   env:
      #     CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Upload to Wago.io
        run: |
          curl -X POST "https://addons.wago.io/api/projects/globalplayed/upload" \
          -H "Authorization: Bearer ${{ secrets.WAGO_API_KEY }}" \
          -H "Content-Type: multipart/form-data" \
          -F "file=@GlobalPlayed-${{ github.ref_name }}.zip"
