# This is a basic workflow to help you get started with Actions

name: Package for CurseForge

on:
  create:
    tags:
      - '*'

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Verify all files
        run: py ci/verify.py $(git tag --points-at HEAD)

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Remove useless folders for release
        run: rm -rf .git/ .github/

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ../
          zip -r GlobalPlayed.zip ./GlobalPlayed/
