name: Package for CurseForge

on:
  create:
    tags:
      - '*.*.*'


jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Verify all files
        run: python .github/workflows/verify.py $(git tag --points-at HEAD)


  build:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v2

      - name: Remove useless folders for release
        run: rm -rf .git/ .github/

      - name: Uploading package
        uses: actions/upload-artifact@v4
        with:
          name: GlobalPlayed
          path: /home/runner/work/GlobalPlayed/
          if-no-files-found: error
